spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: termoword
  
  # Configuração da conexão com o banco de dados PostgreSQL
  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"

  # Java Persistence API (JPA) configuração
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  
server:
  port: 8080
